name: "Gitee Pages Action"
description: "GitHub Action for Gitee Pages"
author: "yanglbme"
branding:
  icon: "git-branch"
  color: "gray-dark"
inputs:
  gitee-username: psych-future
    description: ""
    required: true
  gitee-password: 
    description: ""
    required: true
  gitee-repo: psych-future/pf-hexo
    description: ""
    required: true
  branch:
    description: "Which branch to build"
    required: false
    default: "master"
  directory:
    description: "Which directory to build"
    required: false
    default: ""
  https:
    description: "Use force https or not"
    required: false
    default: "true"
runs:
  using: "docker"
  image: "Dockerfile"
