name: Sync

on:
  push:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'git@github.com:psych-future/pf-hexo.git'
    steps:
      - name: Sync to Gitee
        uses: psych-future/pf-hexo@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:psych-future/pf-hexo.git
          destination-repo: git@gitee.com:psych-future/pf-hexo.git
